name: Generate Go Artifacts

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.20']

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install dependencies
        run: go get .
      - name: Generate Output
        run: go run ireland-tariffs.go
      - name: List Output
        run: ls        
     # - name: Upload Go test results
     #   uses: actions/upload-artifact@v3
     #   with:
     #     name: Generated JSON Data
     #     path: *.json
