name: Generate Go Artifacts

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.20']

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
          
      - name: Install dependencies
        run: go install .
        
      - name: Generate Output
        run: go run ireland-tariffs.go
        
      - name: Upload Go Output
        uses: skx/github-action-publish-binaries@release-1.3
        if: startsWith(github.ref, 'refs/tags/')        
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "*.json"
